nexacorp-interfaces:site:
- name: siege
  interface:
  - name: GigabitEthernet0/1
    description: "Lien vers coeur de reseau"
    enabled: up
    vlan-id: 10
- name: agence1
  interface:
  - name: GigabitEthernet0/1
    description: "LAN utilisateurs agence1"
    enabled: up
    vlan-id: 30
- name: agence2
  interface:
  - name: GigabitEthernet0/1
    description: "LAN utilisateurs agence2"
    enabled: up
    vlan-id: 40
