services:
  siege-router:
    build:
      context: ..
      dockerfile: lab/Dockerfile
    container_name: siege-router
    environment:
      - SITE_NAME=siege
      - API_TOKEN=${API_TOKEN}
    ports:
      - "5001:5000"
    networks:
      - nexacorp-lab

  agence1-router:
    build:
      context: ..
      dockerfile: lab/Dockerfile
    container_name: agence1-router
    environment:
      - SITE_NAME=agence1
      - API_TOKEN=${API_TOKEN}
    ports:
      - "5002:5000"
    networks:
      - nexacorp-lab

  agence2-router:
    build:
      context: ..
      dockerfile: lab/Dockerfile
    container_name: agence2-router
    environment:
      - SITE_NAME=agence2
      - API_TOKEN=${API_TOKEN}
    ports:
      - "5003:5000"
    networks:
      - nexacorp-lab

  agence3-router:
    build:
    context: ..
    dockerfile: lab/Dockerfile
    container_name: agence3-router
    environment:
      - SITE_NAME=agence3
      - API_TOKEN=${API_TOKEN}
    ports:
      - "5004:5000"
    networks:
      - nexacorp-lab

networks:
  nexacorp-lab:
    driver: bridge
